name: Release
on:
  push:    
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Extract version from tag
        id: ver
        run: echo "value=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      # 3) Pack com a versão vinda da tag
      - name: Pack
        run: >
          dotnet pack src/UnixDomainSockets.HttpClient/UnixDomainSockets.HttpClient.csproj
          -c Release
          -o .artifacts
          /p:ContinuousIntegrationBuild=true
          /p:Version=${{ steps.ver.outputs.value }}

      # 4) Publica .nupkg
      - name: Push NuGet package
        run: >
          dotnet nuget push ".artifacts/*.nupkg"
          --source https://api.nuget.org/v3/index.json
          --api-key ${{ secrets.UNIXDOMAINSOCKETS }}
          --skip-duplicate
      
      - name: Push Symbols
        run: >
          dotnet nuget push ".artifacts/*.snupkg"
          --source https://api.nuget.org/v3/index.json
          --api-key ${{ secrets.UNIXDOMAINSOCKETS }}
          --skip-duplicate
